version: '3.4'

services:
  smartaccess.administration.api:
    image: ${DOCKER_REGISTRY-}smartaccessadministrationapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7000
      - ASPNETCORE_HTTPS_PORTS=7001
    ports:
      - "7000:7000"
      - "7001:7001"
    build:
      context: .
      dockerfile: SmartAccess.Administration.API/Dockerfile
    depends_on:
        - SqlServerDb

  smartaccess.locking.api:
    image: ${DOCKER_REGISTRY-}smartaccesslockingapi
    ports:
    - 6000:6000
    build:
      context: .
      dockerfile: SmartAccess.Locking.API/Dockerfile
    depends_on:
        - SqlServerDb

  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Password123# 

