services:
  todoapi:
    image: testprjapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on: 
      - migrations
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
    - "8082:1433"